// Единственный словарь видимых строк. В остальных файлах русских текстов нет.
export const strings = {
  app: {
    title: "Разметка схем",
    subtitle: "Метки на планах помещений",
  },
  header: {
    project: "Объект",
    noProject: "Объект не выбран",
  },
  panels: {
    tools: "Инструменты",
    schemes: "Схемы",
    marks: "Метки",
    properties: "Свойства",
    canvasEmpty: "Загрузите план схемы, чтобы начать разметку",
    marksEmpty: "Меток пока нет — выберите тип и щёлкните по плану",
  },
  project: {
    untitled: "Новый объект",
    defaultSchemeName: "Схема 1",
  },
  categories: {
    light: "Свет",
    switches: "Выключатели",
    sockets: "Розетки",
    climate: "Климат",
    network: "Сетевое оборудование",
  },
  types: {
    spot: "Точечный светильник",
    lamp: "Светильник",
    bedLight: "Подсветка кровати",
    track: "Трек",
    backlight: "Подсветка",
    strip: "Лента",
    wardrobeLight: "Подсветка шкафа",
    switch: "Выключатель",
    switchDouble: "Выключатель двойной",
    socket: "Розетка",
    breezer: "Бризер",
    conditioner: "Кондиционер",
    wifi: "WiFi точка",
  },
  shapes: {
    circle: "Круг",
    "circle-cross": "Круг с крестом",
    "circle-dot": "Круг с точкой",
    "circle-fill": "Круг закрашенный",
    "circle-half": "Круг наполовину закрашенный",
    square: "Квадрат",
    "square-cross": "Квадрат с крестом",
    "square-fill": "Квадрат закрашенный",
    triangle: "Треугольник",
    "triangle-down": "Треугольник вершиной вниз",
    star: "Звезда",
    diamond: "Ромб",
    "diamond-fill": "Ромб закрашенный",
    hexagon: "Шестиугольник",
    plus: "Крест",
    inherit: "Как у категории",
  },
  blockMode: {
    each: "Каждая точка — своя метка",
    single: "Одна метка на блок",
  },
  tools: {
    type: "Тип метки",
    noType: "Тип не выбран",
    chooseType: "Выбрать тип",
    changeType: "Сменить тип",
    changeTypeHint: "Сменить тип выделенной метки — номер выдастся новый",
    kind: "Что ставим",
    kindPoint: "Точка",
    kindLine: "Линия",
    kindPointHint: "Клик по плану ставит точку выбранного типа",
    kindLineHint: "Клики рисуют ломаную: лента или трек",
    block: "Блок точек",
    blockHint: "Режим блока хранится у типа метки",
    sizes: "Размеры",
    markSize: "Метки",
    labelSize: "Подписи",
    zoom: "Масштаб",
    zoomIn: "Приблизить",
    zoomOut: "Отдалить",
    zoomFit: "Вписать план",
    zoomReset: "100 %",
    undo: "Отменить",
    redo: "Вернуть",
    undoTitle: "Отменить: {label} (Ctrl+Z)",
    redoTitle: "Вернуть: {label} (Ctrl+Y)",
    selectMode: "Выделение",
    noSelection: "Метка не выделена",
  },
  picker: {
    title: "Тип метки",
    search: "Буква или название",
    empty: "Ничего не нашлось — введите букву нового кода",
    createTitle: "Нового типа «{code}» ещё нет",
    createName: "Название",
    createNamePlaceholder: "Например: Розетка в полу",
    createCategory: "Категория",
    create: "Создать тип",
    created: "Тип {code} — {name} добавлен",
    codeHint: "Код типа — одна или две буквы",
  },
  canvas: {
    hintSelect: "Выберите тип метки, чтобы ставить метки по плану",
    hintPoint:
      "Клик ставит {label}. Ручки «+» у метки — соседняя точка блока. Esc снимает выделение и прячет ручки, второй Esc выходит из режима.",
    hintSelectMode:
      "Клик выбирает метку, перетаскивание двигает её или подпись, Delete удаляет, Esc снимает выделение.",
    hintLine: "Клик — вершина. Двойной клик по последней завершает линию, по первой — замыкает. Backspace — убрать вершину, Esc — отменить.",
    lineTooShort: "Линия из одной точки не сохраняется — поставьте ещё хотя бы одну вершину",
    needType: "Сначала выберите тип метки",
    needScheme: "Сначала загрузите план схемы",
    deleteBlockTitle: "Удалить метку из блока?",
    deleteBlockMessage:
      "Метка «{label}» стоит в блоке из {count}. Удалить только её? Соседние метки останутся на месте.",
    deleteConfirm: "Удалить метку",
    typeChanged: "Теперь это {label}",
    undone: "Отменено: {label}",
    redone: "Возвращено: {label}",
    nothingToUndo: "Отменять нечего",
    nothingToRedo: "Возвращать нечего",
  },
  history: {
    addMark: "постановка метки",
    addBlock: "точка блока",
    addLine: "линия",
    move: "перемещение метки",
    moveLabel: "смещение подписи",
    remove: "удаление метки",
    changeType: "смена типа",
    addType: "новый тип",
    viewSize: "размер меток и подписей",
    blockMode: "режим блока",
    markField: "правка полей метки",
    markRoom: "помещение метки",
    addRoom: "новое помещение",
    renameRoom: "переименование помещения",
    removeRoom: "удаление помещения",
    editType: "правка типа",
    removeType: "удаление типа",
    addCategory: "новая категория",
    editCategory: "правка категории",
    removeCategory: "удаление категории",
  },
  errors: {
    schemeNotFound: "Схема не найдена",
    typeNotFound: "Тип метки не найден",
    markNotFound: "Метка не найдена",
    categoryNotFound: "Категория не найдена",
    roomNotFound: "Помещение не найдено",
    groupNotFound: "Группа не найдена",
    noPoints: "Нужна хотя бы одна точка",
    shortLine: "Линия короче двух вершин не сохраняется",
    codeRequired: "Нужен код типа — одна или две буквы",
    codeTooLong: "Код типа — не больше двух букв",
    codeLetters: "Код типа — только буквы, одна или две",
    blockOnlyForPoints: "Блок собирается только из точек, линию в блок не поставить",
    codeTaken: "Код {code} уже занят",
    nameRequired: "Нужно название",
    typeHasMarks: "Тип {code} используют метки ({count}) — сперва смените им тип",
    categoryHasTypes: "В категории есть типы — сперва перенесите или удалите их",
    unknownShape: "Неизвестная форма",
    unknownBlockMode: "Неизвестный режим блока",
    unknownSide: "Неизвестная сторона блока",
    unknownKind: "Неизвестный вид метки",
    notAProject: "Файл не похож на проект разметки схем",
    archiveBroken: "Архив повреждён — не удалось прочитать содержимое",
    noProjectJson: "В архиве нет project.json — это не файл разметки схем",
    brokenProjectJson: "Данные проекта в архиве повреждены и не читаются",
    archiveTooBig: "Проект слишком большой для одного файла — больше 4 ГБ",
    zip64Unsupported: "Архив в формате zip64 — такие файлы здесь не читаются, пересоберите обычным zip",
    imagesNotMap: "Картинки для упаковки передаются Map «идентификатор → файл»",
    foreignProject: "Данные в файле не похожи на объект разметки схем",
    futureVersion: "Файл сделан более новой версией программы (формат {version}, здесь {current}) — обновите страницу",
  },
  problems: {
    duplicateCode: "Код типа {code} встречается больше одного раза",
    markWithoutType: "У метки нет типа из справочника",
    markWithoutScheme: "Метка ссылается на несуществующую схему",
    markWithoutRoom: "Метка ссылается на несуществующее помещение",
    duplicateNumber: "Обозначение {label} выдано больше одного раза",
    emptyPoints: "У метки нет точек",
    shortLine: "У линии меньше двух вершин",
    smallGroup: "В группе меньше двух меток",
    groupAcrossSchemes: "Метки одной группы лежат на разных схемах",
    counterBehind: "Счётчик типа {code} меньше выданных номеров",
    typeWithoutCategory: "У типа нет категории из справочника",
  },
  file: {
    readme: `Разметка схем — файл проекта

Объект: {name}
Выгружено: {date}
Схем: {schemes}, меток: {marks}
Версия формата: {version}

Что это
  Обычный zip-архив с разметкой планов помещений: цветные метки с обозначениями
  (Т1, В3, Р7) поверх картинок планов.

Что внутри
  project.json   — весь объект: категории, типы меток, помещения, схемы, метки,
                   группы и счётчики номеров. Координаты меток — доли от размера
                   плана (0…1), поэтому не зависят от масштаба картинки.
  schemes/       — изображения планов как есть, без пережатия. Имя файла —
                   идентификатор изображения, на него ссылается поле imageId
                   схемы в project.json.
  README.txt     — этот файл.

Чем открыть
  Страницей «Разметка схем»: «Открыть файл» и выбрать этот архив. Загрузится
  весь объект вместе с планами — на любом компьютере и в любом браузере,
  подключение к сети не нужно.
  Содержимое можно посмотреть и обычным распаковщиком: планы лежат картинками,
  данные — текстом в JSON.

Если страницы под рукой нет
  project.json читается любым текстовым редактором, а схемы открываются как
  обычные картинки: данные не пропадут, даже если программы не окажется.`,
  },
  projects: {
    switch: "Переключить объект",
    create: "Новый объект",
    createTitle: "Создать объект",
    rename: "Переименовать объект",
    renameTitle: "Имя объекта",
    namePlaceholder: "Квартира на Ленина",
    remove: "Удалить объект",
    removeTitle: "Удалить объект?",
    removeMessage:
      "Объект «{name}» со всеми схемами, метками и планами будет удалён. Вернуть его будет неоткуда.",
    created: "Объект «{name}» создан",
    removed: "Объект «{name}» удалён",
    welcomeTitle: "Начнём с объекта",
    welcomeText:
      "Объект — это дом или квартира. Внутри — схемы этажей, на них метки. Всё хранится в вашем браузере.",
    empty: "Объектов пока нет",
  },
  schemes: {
    add: "Загрузить план",
    addHint: "Перетащите PNG или JPG на план — или нажмите «Загрузить план»",
    dropHere: "Отпустите — план загрузится",
    edit: "Править план",
    rename: "Переименовать схему",
    renameTitle: "Имя схемы",
    remove: "Удалить схему",
    removeTitle: "Удалить схему?",
    removeMessage: "Схема «{name}» будет удалена вместе с метками ({marks}). Вернуть её будет неоткуда.",
    up: "Выше",
    down: "Ниже",
    defaultName: "Схема {number}",
    size: "{width} × {height}",
    added: "Схема «{name}» добавлена",
    removed: "Схема «{name}» удалена",
    loading: "Читаем план…",
    noImage: "План не загружен",
  },
  image: {
    editTitle: "План схемы",
    rotateLeft: "Повернуть влево",
    rotateRight: "Повернуть вправо",
    cropHint: "Обведите рамкой то, что оставить, и нажмите «Обрезать»",
    crop: "Обрезать",
    cropReset: "Снять рамку",
    apply: "Готово",
    wrongType: "Нужен PNG или JPG",
    broken: "Не удалось прочитать картинку — попробуйте другой файл",
    working: "Готовим план…",
    applied: "План обновлён, метки остались на своих местах",
    outsideTitle: "Метки за рамкой",
    marksOutsideAsk:
      "За рамкой останется меток: {count}. Их прижмёт к краю плана, прежних мест уже не вернуть. Обрезать так?",
    cropAnyway: "Обрезать так",
    appliedClamped: "План обновлён; меток прижато к краю: {count}",
  },
  storage: {
    memory: "Браузер не дал открыть хранилище — работаем в памяти. Выгрузите объект в файл, иначе работа пропадёт при закрытии вкладки.",
    writeFailed: "Браузер не дал записать данные — работа осталась в памяти. Выгрузите объект в файл.",
    lowSpace: "В браузере осталось меньше {free} свободного места — выгрузите объект в файл.",
  },
  marks: {
    count: "Показано {shown} из {total}",
    room: "Помещение",
    location: "Расположение",
    locationPlaceholder: "Например: над тумбой слева",
    original: "В оригинальной схеме",
    originalPlaceholder: "Например: В31",
    nothingFound: "Под фильтр ничего не подошло",
    focus: "Показать метку на плане",
  },
  filters: {
    search: "Поиск по меткам",
    searchPlaceholder: "Обозначение, расположение, оригинал",
    room: "Помещение",
    allRooms: "Все помещения",
    types: "Категории и типы",
    hidden: "скрыто: {count}",
    showAll: "Показать все",
  },
  rooms: {
    title: "Помещения объекта",
    open: "Помещения",
    add: "Добавить",
    namePlaceholder: "Спальная Оли",
    newRoom: "Новое помещение…",
    newTitle: "Название помещения",
    none: "Без помещения",
    empty: "Помещений пока нет — впишите помещение в строке метки",
    marks: "меток: {count}",
    remove: "Удалить помещение",
    removeTitle: "Удалить помещение?",
    removeMessage: "Помещение «{name}» будет удалено, у меток ({count}) поле опустеет.",
  },
  dictionary: {
    open: "Справочник типов",
    title: "Справочник объекта",
    categories: "Категории",
    types: "Типы меток",
    code: "Код типа",
    name: "Название",
    category: "Категория",
    shape: "Форма",
    color: "Цвет категории",
    marks: "Меток этого типа",
    noTypes: "Типов пока нет",
    codePlaceholder: "В",
    typeNamePlaceholder: "Выключатель",
    categoryNamePlaceholder: "Шторы",
    addType: "Добавить тип",
    addCategory: "Добавить категорию",
    removeType: "Удалить тип",
    removeTypeTitle: "Удалить тип?",
    removeTypeMessage: "Тип «{code} — {name}» исчезнет из справочника этого объекта.",
    removeCategory: "Удалить категорию",
    removeCategoryTitle: "Удалить категорию?",
    removeCategoryMessage: "Категория «{name}» исчезнет из справочника этого объекта.",
    saveTemplate: "Сохранить как шаблон",
    saveTemplateHint: "Новые объекты начнутся с этого справочника; уже созданные останутся как есть",
    templateSaved: "Справочник сохранён как шаблон для новых объектов",
    resetTemplate: "Вернуть стандартный шаблон",
    templateReset: "Новые объекты снова начнутся со стандартного справочника",
  },
  tables: {
    label: "Обозначение",
    type: "Тип",
    room: "Помещение",
    location: "Расположение",
    original: "В оригинале",
    code: "Код",
    name: "Название",
    category: "Категория",
    color: "Цвет",
    shape: "Форма",
    marksTitle: "Метки объекта",
    typesTitle: "Справочник типов",
    noRoom: "Без помещения",
    onlyShown: "Показаны только: {names}",
    partial: "Часть меток скрыта фильтром — лист неполный",
  },
  exportPanel: {
    tableTitle: "Таблица",
    tableDialog: "Таблица меток",
    schemeTitle: "Схема",
    schemeDialog: "Выгрузить схему",
    groupBy: "Разбивка",
    groupByCategory: "По категориям",
    groupByType: "По типам",
    groupByRoom: "По помещениям",
    kind: "Таблица",
    kindMarks: "Метки",
    kindTypes: "Справочник типов",
    currentScheme: "Только текущая схема",
    area: "Что выгружаем",
    areaAll: "Вся схема",
    areaView: "Как вижу на экране",
    withLegend: "С легендой в углу",
    scale: "Множитель",
    size: "{width} × {height} px · {mmWidth} × {mmHeight} мм при 300 dpi",
    rows: "Строк: {count}",
    csv: "CSV для Excel",
    markdown: "Markdown",
    copy: "Копировать",
    png: "Картинкой PNG",
    print: "Печать",
    download: "Скачать PNG",
    allSchemes: "Все схемы (zip)",
    copied: "Таблица скопирована — вставляйте в Таблицы",
    copyFailed: "Браузер не дал доступ к буферу обмена",
    saved: "Файл «{name}» выгружен",
    noMarks: "Меток пока нет — выгружать нечего",
    noScheme: "Схема не выбрана",
    noImage: "У схемы нет плана",
    schemesDone: "Схем в архиве: {count}",
    busy: "Готовим файл…",
    tooBig: "Слишком большая картинка — уменьшите множитель",
    failed: "Не удалось собрать файл",
  },
  dialog: {
    confirm: "Да, удалить",
    cancel: "Отмена",
    save: "Сохранить",
    close: "Закрыть",
  },
  units: {
    megabytes: "{value} МБ",
  },
  notify: {
    close: "Закрыть",
  },
};

// strings.errors.codeTaken и подобные — шаблоны с {переменными}.
export function text(key, vars) {
  let value = key.split(".").reduce((node, part) => (node == null ? node : node[part]), strings);
  if (typeof value !== "string") return key;
  if (vars) {
    for (const [name, replacement] of Object.entries(vars)) {
      value = value.split("{" + name + "}").join(String(replacement));
    }
  }
  return value;
}
